# Data: abril 2025
# Autores:
# - Inês Mendes
# - Margarida Tavares
# - Tomás Franco

trigger:
  branches:
    include:
      - '*'

pr:
  branches:
    include:
      - main

variables:
  venvDir: '.venv'

stages:
  - stage: CI
    displayName: 'Integração Contínua (CI)'
    condition: succeeded()
    jobs:
      - job: Lint
        displayName: 'Lint em app.py da branch main'
        pool:
          name: 'grupo2'
        steps:
          - script: |
              python3 -m venv $(venvDir)
              source $(venvDir)/bin/activate
              pip install --upgrade pip
              pip install flake8
              git fetch origin main
              git checkout origin/main -- app.py
              flake8 app.py
            displayName: 'Executar flake8 em app.py (main)'

  - stage: CD
    displayName: 'Entrega Contínua (CD)'
    condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest'))
    jobs:
      - job: ValidarPR
        displayName: 'Validação no Pull Request'
        pool:
          name: 'grupo2'
        steps:
          - script: |
              python3 -m venv $(venvDir)
              source $(venvDir)/bin/activate
              pip install --upgrade pip
              pip install -r requirements.txt
              echo "Aqui podes rodar testes, validadores ou builds"
            displayName: 'Preparar ambiente e validar PR'





