# Data: abril 2025
# Autores:
# - Inês Mendes
# - Margarida Tavares
# - Tomás Franco

trigger:
  branches:
    include:
      - '*'

pr:
  branches:
    include:
      - main

variables:
  venvDir: '$(Build.SourcesDirectory)/.venv'
  requirementsFile: 'requirements.txt'
  buildOutputDir: '$(Build.ArtifactStagingDirectory)'

stages:
  - stage: CI
    displayName: 'Integração Contínua (CI)'
    condition: succeeded()
    jobs:
      - job: Lint
        displayName: 'Lint em ficheiros python'
        pool:
          name: 'grupo2'
        steps:
          - script: |
              python3 -m venv $(venvDir)
              . $(venvDir)/bin/activate
              pip install --upgrade pip
              pip install flake8
              git fetch origin main
              git fetch origin develop
              git checkout origin/main -- *.py
              git checkout origin/develop -- *.py
              flake8 *.py 
            displayName: 'Executar flake8 nos ficheiros Python'
      
      - job: Teste_unitario
        displayName: 'Executar testes unitários'
        pool:
          name: 'grupo2'
        steps:
          - script: |
              python3 -m venv $(venvDir)
              . $(venvDir)/bin/activate
              pip install --upgrade pip 
              pip install -r $(requirementsFile)
              python3 teste_aceitacao.py --maxfail=1 -v
            displayName: 'Executar testes de unitário'

      - job: Teste_aceitacao
        displayName: 'Executar testes de aceitação'
        pool:
          name: 'grupo2'
        steps:
          - script: |
              python3 -m venv $(venvDir)
              . $(venvDir)/bin/activate
              pip install --upgrade pip 
              pip install -r $(requirementsFile)
              pytest teste_aceitacao.py --maxfail=1 -v
            displayName: 'Executar testes de aceitação'

  - stage: Build
    displayName: 'Build do Projeto'
    condition: succeeded()
    jobs:
      - job: BuildJob
        displayName: 'Construção e empacotamento do código'
        pool:
          name: 'grupo2'
        steps:
          - script: |
              python3 -m venv $(venvDir)
              . $(venvDir)/bin/activate
              pip install --upgrade pip setuptools wheel
              pip install --upgrade pip
              pip install -r $(requirementsFile)
              echo "Build em andamento..."
              python setup.py sdist bdist_wheel
            displayName: 'Compilar o projeto e gerar pacotes'

          - publish: $(Build.ArtifactStagingDirectory)
            artifact: drop
            displayName: 'Publicar artefatos gerados'

  - stage: CD
    displayName: 'Entrega Contínua (CD)'
    condition: eq(variables['Build.Reason'], 'PullRequest')
    jobs:
      - job: DeployViaDocker
        displayName: 'Buildar imagem, enviar para ACR e atualizar ACI'
        pool:
          vmImage: 'ubuntu-latest'
        steps:

          - task: Docker@2
            displayName: 'Build e Push da imagem para o ACR'
            inputs:
              containerRegistry: 'grupo2'
              repository: 'imagem_grupo2'
              command: 'buildAndPush'
              Dockerfile: '**/dockerfile'
              tags: |
                pr-$(System.PullRequest.PullRequestId)

          - script: |

              echo "Atualizando Azure Container Instance com nova imagem do PR..."
              az container create \
                --name grupo2 \
                --resource-group RG-UPSKILL-SysAdmin \
                --image grupo2.azurecr.io/imagem_grupo2:pr-$(System.PullRequest.PullRequestId) \
                --cpu 1 \
                --memory 1 \
                --registry-username "grupo2" \
                --registry-password "ec3y18r3wFifB8lYacqEDa3VM4xmJoIAwKv1JYrGcb+ACRBPjFnH" \
                --dns-name-label grupo2-api \
                --ports 5000 \
                --restart-policy Always
            displayName: 'Atualizar Container Instance com nova imagem'







