# Data: abril 2025
# Autores:
# - Inês Mendes
# - Margarida Tavares
# - Tomás Franco

pr:
  branches:
    include:
      - main

variables:
  venvDir: '$(Build.SourcesDirectory)/.venv'
  requirementsFile: 'requirements.txt'
  buildOutputDir: '$(Build.ArtifactStagingDirectory)'

stages:
  - stage: CD
    displayName: 'Entrega Contínua (CD)'
    condition: eq(variables['Build.Reason'], 'PullRequest')
    jobs:
      - job: DeployToVM
        displayName: 'Deploy com Git Clone na VM'
        pool:
          name: 'grupo2'
        steps:
          - script: |
              echo "Conectando à VM via SSH..."

              ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa grupo2@68.221.133.230 "
                echo "A apagar a pasta antiga..."
                rm -rf /home/grupo2/m6p2

                echo "A clonar repositório..."
                git clone https://github.com/ines2357/m6p2.git /home/grupo2/m6p2

                cd /home/grupo2/m6p2

                python3 -m venv .venv
                source .venv/bin/activate
                pip install -r requirements.txt

                echo 'A executar app.py em segundo plano...'
                nohup python3 app.py > flask.log 2>&1 &
              "
            displayName: 'Clonar código e executar app.py na VM'
