# Data: abril 2025
# Autores:
# - Inês Mendes
# - Margarida Tavares
# - Tomás Franco

trigger: none 

pr:
  branches:
    include:
      - main

stages:
  - stage: CD
    displayName: 'Entrega Contínua (CD)'
    condition: eq(variables['Build.Reason'], 'PullRequest')
    jobs:
      - job: BuildAndPushDockerImage
        displayName: 'Build da imagem Docker e envio para ACR'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: Docker@2
            displayName: 'Build e Push da imagem para o ACR'
            inputs:
              containerRegistry: 'grupo2'
              repository: 'imagem_grupo2'
              command: 'buildAndPush'
              Dockerfile: '**/dockerfile'
              tags: |
                pr-$(System.PullRequest.PullRequestId)

      - job: UpdateContainerInstance
        displayName: 'Atualizar ACI com a nova imagem Docker'
        dependsOn: BuildAndPushDockerImage
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - script: |
              echo "Atualizando Azure Container Instance com nova imagem do PR..."
              az container create \
                --name grupo2 \
                --resource-group RG-UPSKILL-SysAdmin \
                --image grupo2.azurecr.io/imagem_grupo2:pr-$(System.PullRequest.PullRequestId) \
                --cpu 1 \
                --memory 1 \
                --registry-username "grupo2" \
                --registry-password "ec3y18r3wFifB8lYacqEDa3VM4xmJoIAwKv1JYrGcb+ACRBPjFnH" \
                --dns-name-label grupo2-api \
                --ports 5000 \
                --restart-policy Always
            displayName: 'Atualizar Container Instance com nova imagem'
